[package]
name = "git-cvs-fast-import"
version = "0.1.0"
edition = "2018"

[workspace]
members = [ "comma-v", "eq-macro", "git-fast-import", "patchset", "rcs-ed", "store" ]

[dev-dependencies]
tokio-test = "0.4.2"

[dependencies]
anyhow = "1.0.43"
binary-heap-plus = "0.4.1"
comma-v = { path = "comma-v" }
flume = "0.10.8"
futures = "0.3.17"
git-cvs-fast-import-store = { path = "store" }
git-fast-import = { path = "git-fast-import" }
log = "0.4.14"
num_cpus = "1.13.0"
parse_duration = "2.1.1"
patchset = { path = "patchset" }
pretty_env_logger = "0.4.0"
rcs-ed = { path = "rcs-ed" }
structopt = "0.3.22"
tempfile = "3.2.0"
thiserror = "1.0.26"
tokio = { version = "1.10.0", features = ["macros", "rt-multi-thread", "signal", "sync", "time", "fs"] }

[features]
