[package]
name = "git-cvs-fast-import"
version = "0.1.0"
edition = "2018"

[workspace]
members = [ "comma-v", "eq-macro", "git-fast-import", "internal/process", "internal/state", "internal/store", "patchset", "rcs-ed" ]

[dev-dependencies]
tokio-test = "0.4.2"

[dependencies]
anyhow = "1.0.44"
comma-v = { path = "comma-v" }
flume = "0.10.9"
git-cvs-fast-import-process = { path = "internal/process" }
git-cvs-fast-import-state = { path = "internal/state" }
git-cvs-fast-import-store = { path = "internal/store" }
git-fast-import = { path = "git-fast-import" }
log = "0.4.14"
num_cpus = "1.13.0"
parse_duration = "2.1.1"
patchset = { path = "patchset" }
pretty_env_logger = "0.4.0"
rcs-ed = { path = "rcs-ed" }
structopt = "0.3.23"
tempfile = "3.2.0"
thiserror = "1.0.29"
tokio = { version = "1.12.0", features = ["io-util", "macros", "process", "rt-multi-thread", "signal", "sync", "time", "fs"] }

[features]
