[package]
name = "rcs-ed"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.45"
nom = "7.1.0"
thiserror = "1.0.30"

[dev-dependencies]
structopt = "0.3.25"
