[package]
name = "rcs-ed"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.43"
nom = "6.2.1"
thiserror = "1.0.26"

[dev-dependencies]
structopt = "0.3.22"
