[package]
name = "git-cvs-fast-import-state"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
derive_more = "0.99.16"
git-fast-import = { path = "../../git-fast-import" }
log = "0.4.14"
serde = { version = "1.0.130", features = ["derive", "rc"] }
thiserror = "1.0.29"
tokio = { version = "1.13.0", features = ["io-util", "sync"] }

[features]
