name: goreleaser

on:
  push:
    tags:
      - 'v[0-9]*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Unsurprisingly, we need Go to run goreleaser.
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # We need a Rust toolchain, but specifically only the
      # x86_64-unknown-linux-musl target.
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.55.0
          target: x86_64-unknown-linux-musl
          override: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
