[package]
name = "git-fast-import"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.16"
nom = "7.0.0"
rev_lines = "0.2.1"
thiserror = "1.0.29"
